#!/bin/bash
unset IFS
set -eu

if [ -z "${DEST:-}" ]; then
    exit
fi

mkdir -p "$DEST"

lookup_apps() {
    cargo metadata \
        --format-version 1 \
        --no-deps |
        jq -r '.packages[0].targets.[] | select(.kind | index("bin") != null).name'
}

apps_output="$(lookup_apps)"

apps=()

while IFS=$'\n' read -r line; do
    apps+=("$line")
done <<<"$apps_output"

for app in "${apps[@]}"; do
    cp "target/release/$app" "$DEST"
done
