---
name: "Test-Futureproof-Dependencies"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test-Futureproof-Dependencies:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions-rust-lang/setup-rust-toolchain@v1"
      with:
        toolchain: "1.86.0"
    - name: "provision dev dependencies"
      run: |
        make -j 4 crates
        cargo install --force --path .
    - run: |
        cd example
        crit -l
