---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions-rust-lang/setup-rust-toolchain@v1"
    - name: "provision dev tools"
      run: "make -j 4 crates"
    - run: "tinyrick test"
